import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/components/layout/Layout";
import { QueryClientProvider } from "@tanstack/react-query";
import ReactQueryProvider from "@/utils/providers/ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
          <body className={inter.className}>
            <ReactQueryProvider>
               <Layout>
                  {children}  
                </Layout>
            </ReactQueryProvider>
           
          </body>
    </html>
  );
}
